development:
  adapter: postgresql
  encoding: unicode
  database: api_development
  username: api
  password: 777
  min_messages: warning
  pool: 10

test:
  adapter: postgresql
  encoding: unicode
  database: api_test
  username: api
  password: 777
  min_messages: warning
  pool: 10
